name: Deploy to Azure

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set Commit ID as Tag
        run: echo "COMMIT_ID=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker Image for service-hello
        env:
          COMMIT_ID: ${{ env.COMMIT_ID }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
        run: |
          docker build -t $ACR_NAME.azurecr.io/$CONTAINER_REGISTRY:$COMMIT_ID -f ./service-hello/Dockerfile .

      - name: Push Docker Image to Azure Container Registry
        env:
          COMMIT_ID: ${{ env.COMMIT_ID }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
        run: |
          docker push $ACR_NAME.azurecr.io/$CONTAINER_REGISTRY:$COMMIT_ID

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ilhaminternnawa
          minimum-approvals: 1
          issue-title: "Manual Approval Required"
          issue-body: "Please approve or deny the deployment for this change."

  deploy-to-containerapps:
    name: Deploy to Container Apps
    needs: manual-approval  
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Commit ID as Tag
        run: echo "COMMIT_ID=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install Azure CLI containerapp extension
        run: |
          az extension add --name containerapp --upgrade || echo "containerapp extension already installed"

      - name: Deploy service-hello
        env:
          CONTAINER_APP_NAME: ${{ secrets.CONTAINER_APP_NAME }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          COMMIT_ID: ${{ env.COMMIT_ID }}
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
        run: |
          az containerapp update --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --image $ACR_NAME.azurecr.io/$CONTAINER_REGISTRY:$COMMIT_ID

  deploy-to-aks:
    name: Deploy to AKS
    needs: manual-approval  
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Commit ID as Tag
        run: echo "COMMIT_ID=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set The Cluster Subscription
        run: az account set --subscription ${{ secrets.AKS_SUBSCRIPTION }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        env:
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          COMMIT_ID: ${{ env.COMMIT_ID }}
        run: |
          kubectl set image deployment/service-hello-deployment service-hello=${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.CONTAINER_REGISTRY }}:${{ env.COMMIT_ID }} -n devops-2